add explicit path to UEFI OVMF_VARS template to ensure that libvirt knows which template to use - seems to be issue on Fedora 30 hosts as of now
Providing this on other distributions seems to not interfere.

The error from Fedora 30 that appears when this is not in place is
below:
...
error: operation failed: unable to find any master var store for loader: /usr/share/OVMF/OVMF_CODE.fd
...